# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 091e06af4ceeee7513d7ce9cb74b23c13cbc5f8dc8ff1de295a4a4ab7403ddd0bd23948b47e2fea1a10c966ddf442a3fa1ece4f8f6c3bbe290b998911df9a821

test:
  secret_key_base: 86a8a97019809c586a1ba525c5c31b424be7d0078b25ffcfe4383677006c8bfd8491ae3fd357a29e67ae3d684ad49afe1d8b63988d8afa7c0f911f1d05ad42c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
